'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
'
Namespace net.xmethods.www
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BabelFishBinding", [Namespace]:="http://www.xmethods.net/sd/BabelFishService.wsdl")>  _
    Public Class BabelFishService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://services.xmethods.net:80/perl/soaplite.cgi"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:xmethodsBabelFish#BabelFish", RequestNamespace:="urn:xmethodsBabelFish", ResponseNamespace:="urn:xmethodsBabelFish")>  _
        Public Function BabelFish(ByVal translationmode As String, ByVal sourcedata As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("BabelFish", New Object() {translationmode, sourcedata})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginBabelFish(ByVal translationmode As String, ByVal sourcedata As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("BabelFish", New Object() {translationmode, sourcedata}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndBabelFish(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
